[PLC]
;COM = COM5
COM = COM7
BAUDRATE = 9600

; [SFC]
; COM = COM8
; COM_RC = COM10
; BAUDRATE = 9600

[CAMERA]
IDC1 = 0
IDC2 = 0

[SETTING]
SCAN_LIMIT = 2
IS_OPEN_CAM_PROPS = 0
FOLDER_TO_KEEP = 10
NUM_CAMERA = 1
PROP_EXPOSURE = -6
IS_SAVE_NG_IMAGE = 0

[PATH]
IMAGE_NG_FOLDER = ./image_NG

[THRESH]
BLOCK_SIZE_1 = 91 
C1 = 3 
BLOCK_SIZE_2  = 69 
C2 = 3

[PLC_SIGNALS]
; SCAN_SIGNAL = \x00\x02
; RESET_SIGNAL = \x00\x03
; PASS_SIGNAL = 02
; FAIL_SIGNAL = 03
SCAN_SIGNAL = 2
RESET_SIGNAL = 3
PASS_SIGNAL = 02 
FAIL_SIGNAL = 03




[MES]
MES_APP_NAME = APP_NAME_HERE
MES_INPUT_AUTO_ID = txtscan
MES_INPUT_TYPE = Edit
MES_RESULT_AUTO_ID = ruleresult
MES_RESULT_TYPE = Text
TIME_SLEEP = 0.1
BACKEND = uia
SIGNAL_ERRORS = ["Please scan SN first", "Please scan WorkerOrder first", "The scan content is incorrect", "Routing Erorr", "Save Error"]
SIGNAL_SUCCESS = ["Please scan lot no", "PASS"]
WAIT_TIME = 1.5
PERCENT_MATCHING = 0.6



; TEST
; MES_APP_NAME = 
; MES_INPUT_AUTO_ID = MainWindow.centralwidget.groupBox.txtscan
; MES_RESULT_AUTO_ID = MainWindow.centralwidget.groupBox_2.ruleresult
; MES_RESULT_TYPE = Edit
; MES_INPUT_TYPE = Edit


; TIME_SLEEP = 0.3
; BACKEND = uia
; SIGNAL_ERRORS = ["Please scan SN first", "Please scan WorkerOrder first", "The scan content is incorrect", "Routing Erorr", "Save Error"]
; SIGNAL_SUCCESS = ["Please scan lot no", "PASS"]
; WAIT_TIME = 1

